### ISSUE TITLE
stream.cz script failed

### ISSUE THREAD

**Issue by wlk-cz** [lzoubek/xbmc-doplnky#304]
Zdravim,
po update na kodi verze 14.2 mi prestal fungovat plugin na stream.cz. Nejspis bude chyba jen u me, protoze stejny problem tu nikdo neresi. Nejspis odlisna verze nejake python knihovny, ale nemuzu nic najit. Kodi provozuji na poslednim archlinuxu.

Log vypada nasledovne:
21:01:44 T:139849822250752   DEBUG: CPythonInvoker(10, /home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py): start processing
21:01:44 T:139849822250752  NOTICE: -->Python Interpreter Initialized<--
21:01:44 T:139849822250752   DEBUG: CPythonInvoker(10, /home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py): the source file to load is "/home/xbmc/.kodi/addons/plugi
21:01:44 T:139849822250752   DEBUG: CPythonInvoker(10, /home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py): setting the Python path to /home/xbmc/.kodi/addons/plugin
21:01:44 T:139849822250752   DEBUG: CPythonInvoker(10, /home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py): entering source directory /home/xbmc/.kodi/addons/plugin.
21:01:44 T:139849822250752   DEBUG: CPythonInvoker(10, /home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py): instantiating addon using automatically obtained id of "p
21:01:44 T:139849822250752   DEBUG: [Stream TV Archiv] Mode: 3
21:01:44 T:139849822250752   DEBUG: [Stream TV Archiv] URL: http://www.stream.cz/API/timeline/latest
21:01:44 T:139849822250752   DEBUG: [Stream TV Archiv] Name: Nejnov.jší videa
21:01:45 T:139849822250752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 400: BAD REQUEST
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py", line 254, in <module>
                                                LIST_EPISODES(url)
                                              File "/home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py", line 144, in LIST_EPISODES
                                                data = getJsonDataFromUrl(url)
                                              File "/home/xbmc/.kodi/addons/plugin.video.dmd-czech.stream/default.py", line 99, in getJsonDataFromUrl
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 400: BAD REQUEST
                                            -->End of Python script error report<--

**Comment by jose1711** [comment]
skusil by som premenovat cely .kodi adresar v home a nakonfigurovat od zaciatku
